export const STAGES = [
  'Sourced',
  'Contacted',
  'NDA Signed',
  'LOI Submitted',
  'Under Diligence',
  'Closed',
];

export const STAGE_CONFIG = {
  'Sourced': {
    accent: 'bg-slate-400',
    badge: 'bg-slate-100 text-slate-600',
    badgeBorder: 'border-slate-200',
    dot: 'bg-slate-400',
    ring: 'ring-slate-300',
    columnHover: 'bg-slate-200/60',
    text: 'text-slate-600',
    lightBg: 'bg-slate-50',
  },
  'Contacted': {
    accent: 'bg-blue-500',
    badge: 'bg-blue-50 text-blue-700',
    badgeBorder: 'border-blue-200',
    dot: 'bg-blue-500',
    ring: 'ring-blue-300',
    columnHover: 'bg-blue-100/60',
    text: 'text-blue-700',
    lightBg: 'bg-blue-50',
  },
  'NDA Signed': {
    accent: 'bg-violet-500',
    badge: 'bg-violet-50 text-violet-700',
    badgeBorder: 'border-violet-200',
    dot: 'bg-violet-500',
    ring: 'ring-violet-300',
    columnHover: 'bg-violet-100/60',
    text: 'text-violet-700',
    lightBg: 'bg-violet-50',
  },
  'LOI Submitted': {
    accent: 'bg-amber-500',
    badge: 'bg-amber-50 text-amber-700',
    badgeBorder: 'border-amber-200',
    dot: 'bg-amber-500',
    ring: 'ring-amber-300',
    columnHover: 'bg-amber-100/60',
    text: 'text-amber-700',
    lightBg: 'bg-amber-50',
  },
  'Under Diligence': {
    accent: 'bg-orange-500',
    badge: 'bg-orange-50 text-orange-700',
    badgeBorder: 'border-orange-200',
    dot: 'bg-orange-500',
    ring: 'ring-orange-300',
    columnHover: 'bg-orange-100/60',
    text: 'text-orange-700',
    lightBg: 'bg-orange-50',
  },
  'Closed': {
    accent: 'bg-emerald-500',
    badge: 'bg-emerald-50 text-emerald-700',
    badgeBorder: 'border-emerald-200',
    dot: 'bg-emerald-500',
    ring: 'ring-emerald-300',
    columnHover: 'bg-emerald-100/60',
    text: 'text-emerald-700',
    lightBg: 'bg-emerald-50',
  },
};

export const INDUSTRIES = [
  'HVAC Services',
  'Landscaping',
  'Medical Billing',
  'IT Managed Services',
  'Plumbing Services',
  'Commercial Cleaning',
  'Pest Control',
  'Auto Repair',
  'Property Management',
  'IT Consulting',
  'Electrical Services',
  'Roofing',
  'Water Treatment',
  'Staffing & Recruiting',
  'Accounting & Tax',
  'Other',
];
